version: "3.8"

# E2E Testing Compose file for Podman
# Orchestrates daemon, web, and loom services for integration testing
#
# Usage:
#   podman-compose -f compose.e2e.yml up -d --build
#   podman-compose -f compose.e2e.yml down -v --remove-orphans

volumes:
  beads-data:  # Shared workspace volume for daemon socket and data

networks:
  e2e-network:
    driver: bridge

services:
  # beads daemon - creates socket and manages data
  daemon:
    build:
      context: ../..
      dockerfile: examples/beads-web-ui/Containerfile.e2e
      target: daemon
    volumes:
      - beads-data:/app/.beads
    healthcheck:
      test: ["CMD", "test", "-S", "/app/.beads/bd.sock"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - e2e-network
    restart: "no"

  # beads-web-ui - serves frontend and API on port 8080
  web:
    build:
      context: ../..
      dockerfile: examples/beads-web-ui/Containerfile.e2e
      target: web
    ports:
      - "8080:8080"
    volumes:
      - beads-data:/app/.beads
    environment:
      - BEADS_SOCKET=/app/.beads/bd.sock
    depends_on:
      daemon:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - e2e-network
    restart: "no"

  # loom server - agent monitoring on port 9000
  loom:
    build:
      context: ../..
      dockerfile: examples/beads-web-ui/Containerfile.e2e
      target: loom
    ports:
      - "9000:9000"
    volumes:
      - beads-data:/app/.beads
    environment:
      - LOOM_CORS_ORIGIN=*
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - e2e-network
    restart: "no"
